name: pyetst
on:
  push:
    branches:
      - main
    paths:
      - 'src/*'
      - 'tests/*'
      - 'config/*'
      - '.github/workflows/*'
  pull_request:
    branches:
        -main
jobs:
  unit-test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: /data
    container: ghcr.io/${{ github.repository }}:latest
    steps:
      - run: pwd
      - uses: actions/checkout@v2
      - run: curl https://nlp100.github.io/data/popular-names.txt > ./work/popular-names.txt
      - run: pytest -s ./tests/
