name: pyetst

on:
  push:
    branches:
      - main
    paths:
      - 'src/*'
      - 'tests/*'
      - 'config/*'
      - '.github/workflows/*'
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository }}:latest
    steps:
      - run: pwd
      - uses: actions/checkout@v2
      - run: cp -r . /data
      - uses: actions/cache@v2
        with:
          id: data-download
          path: /data/work/popular-names.txt
          key: /data/work/popular-names.txt
      - if: steps.data-cdownload.outputs.cache-hit != 'true'
        run: curl https://nlp100.github.io/data/popular-names.txt > /data/work/popular-names.txt
      - run: pytest -s /data/tests/
        working-directory: /data
